/**
 * CSS Variables for ElemText
 *
 * Maps CSS variable names to prop paths.
 * Format: { 'css-var-name': 'prop.path' }
 *
 * These variables are automatically generated by the platform
 * and can be used in PCSS for styling.
 */

export const cssVars = {
    // Typography
    'text_color': 'color',
    'text_font-size': 'fontSize',
    'text_font-weight': 'fontWeight',
    'text_font-family': 'fontFamily',
    'text_line-height': 'lineHeight',
    'text_letter-spacing': 'letterSpacing',
    'text_text-align': 'textAlign',
    'text_text-transform': 'textTransform',
    'text_text-decoration': 'textDecoration',

    // Colors (Designer Panel)
    'text_background-color': 'backgroundColor',
    'text_link-color': 'linkColor',
    'text_link-hover-color': 'linkHoverColor',

    // Spacing
    'text_padding': 'padding',
    'text_margin': 'margin',

    // Border (Designer Panel)
    'text_border-color': 'borderColor',
    'text_border-width': 'borderWidth',
    'text_border-style': 'borderStyle',
    'text_border-radius': 'borderRadius',

    // Effects
    'text_box-shadow': 'boxShadow',
    'text_text-shadow': 'textShadow',
    'text_opacity': 'opacity',

    // Figma-parity stroke props
    'text_stroke-color': 'strokeColor',
    'text_stroke-width': 'strokeWidth',
    'text_stroke-style': 'strokeStyle',
    'text_stroke-opacity': 'strokeOpacity',
    'text_stroke-dasharray': 'strokeDasharray',
    'text_stroke-position': 'strokePosition'
};

/**
 * Designer Panel Configuration — VIBE 2.0 Extension
 *
 * This is additional metadata for the "I'm a Designer" panel.
 * Not used by platform core, but available for enhanced UI.
 */
export const designerConfig = {
    groups: [
        {
            id: 'typography',
            name: 'Typography',
            icon: 'type',
            description: 'Font and text settings',
            vars: ['color', 'fontSize', 'fontWeight', 'fontFamily', 'lineHeight', 'letterSpacing', 'textTransform']
        },
        {
            id: 'spacing',
            name: 'Spacing',
            icon: 'spacing',
            description: 'Padding and margins',
            vars: ['padding', 'margin']
        },
        {
            id: 'effects',
            name: 'Effects',
            icon: 'sparkles',
            description: 'Visual effects',
            vars: ['textShadow', 'opacity']
        }
    ]
};

export default cssVars;
