export const cssVars = {
    menu_height: 'sizeHeight',
    'menu_bg-color': 'widgetColor',
    'menu_border-radius': 'borderRadius',
    'menu_box-shadow': 'shadow',
    'menu-opened_width': 'openWidth',
    menu_color: 'fontColor',
    placeholder_color: 'placeHolderColor',
    'placeholder--active_color': 'backlight',
    'placeholder_font-size': 'placeHolderFontSize',
    'placeholder--multiselect_font-size': 'textPlaceholderMultiCount.placeHolderFontSize',
    'icon_font-size': 'iconFontSize',
    'input-search_bg-color': 'inputBackgroundColor',
    'input-search_color': 'inputColor',
    'input-search_font-size': 'searchFontSize',
    'input-search_margin-left': 'searchModeInput.marginLeft',
    'input-search-prefix_color': 'searchModeInput.prefixColor',
    'input-search-prefix_font-size': 'searchModeInput.prefixFontSize',
    'input-search-prefix_margin-left': 'searchModeInput.prefixMarginLeft',
    'input-search-postfix_font-size': 'searchModeInput.postfixFontSize',
    'input-search-postfix_color': 'searchModeInput.postfixColor',
    'input-search-postfix_margin-right': 'searchModeInput.postfixMarginRight',
    'input-search_border-width': 'searchModeInput.borderWidth',
    'input-search_border-color': 'searchModeInput.borderColor',
    'input-search_border-radius': 'searchModeInput.borderRadius',
    option_color: 'dimensionsColor',
    'selected-option_color': 'selectedDimensionBacklightColor',
    'option_font-size': 'dimensionsFontSize',
    'btn-clear_color': 'btnClear.color',
    'btn-clear_bg-color': 'btnClear.background',
    'btn-clear_font-size': 'btnClear.fontSize',
    'btn-clear__icon_position': 'btnClear.icon.position',
    'btn-clear__icon_color': 'btnClear.icon.style.color',
    'btn-clear__icon_font-size': 'btnClear.icon.style.fontSize',
    'btn-clear__icon_margin': 'btnClear.icon.style.margin',

    'btn-do_color': 'btnDo.color',
    'btn-do_bg-color': 'btnDo.background',
    'btn-do_font-size': 'btnDo.fontSize',
    'btn-do__icon_position': 'btnDo.icon.position',
    'btn-do__icon_color': 'btnDo.icon.style.color',
    'btn-do__icon_font-size': 'btnDo.icon.style.fontSize',
    'btn-do__icon_margin': 'btnDo.icon.style.margin',

    'btn-all_color': 'btnSelectAll.color',
    'btn-all_bg-color': 'btnSelectAll.background',
    'btn-all_font-size': 'btnSelectAll.fontSize',
    'btn-all__icon_position': 'btnSelectAll.icon.position',
    'btn-all__icon_color': 'btnSelectAll.icon.style.color',
    'btn-all__icon_font-size': 'btnSelectAll.icon.style.fontSize',
    'btn-all__icon_margin': 'btnSelectAll.icon.style.margin',

    'checkbox_font-size': 'checkBoxFontSize',
    'radiobutton_font-size': 'radioButtonSettings.size',
    radiobutton_color: 'radioButtonSettings.backlight',
    header_padding: 'headerPadding',
    content_padding: 'contentPadding',
    'content_box-shadow': 'contentBoxShadow',
    'pagination-font-family': 'paginationOptions.fontFamily',
    'pagination-font-size': 'paginationOptions.fontSize',
    'pagination-color': 'paginationOptions.color',
    'pagination-active-color': 'paginationOptions.activeColor',
    'pagination-active-background': 'paginationOptions.activeBackground',
    'dimensions-font-weight': ['dimensionsFontWeight', 'inherit'],
    'placeholder-font-weight': ['placeholderFontWeight', 'inherit'],
    'multiselect--hover': ['multiModeHoverColor', '#0156fd'],
    'input-smart-search-height': ({ isSmartSearch, smartSearchHeight }) =>
        isSmartSearch ? smartSearchHeight ?? 'inherit' : 'inherit',
    'multi-count-size-unit': 'sizeUnit',
    'metric-color': ['metricOptions.color', 'rgba(0, 0, 0, 1)'],
    'metric-font-family': ['metricOptions.fontFamily', 'inherit'],
    'metric-font-size': 'metricOptions.fontSize',
    'metric-font-weight': ['metricOptions.fontWeight', 'inherit'],
    'metric-background-color': 'metricOptions.backgroundColor',
    'metric-text-align': 'metricOptions.textAlign'
};
