export const __webpack_esm_id__=8778;export const __webpack_esm_ids__=[8778];export const __webpack_esm_modules__={63723:(e,t,n)=>{n.d(t,{$H:()=>d,Ay:()=>g});var r=n(83934),o=n(54726),i=function(e,t){return i=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,t){e.__proto__=t}||function(e,t){for(var n in t)Object.prototype.hasOwnProperty.call(t,n)&&(e[n]=t[n])},i(e,t)};function c(e,t){if("function"!==typeof t&&null!==t)throw new TypeError("Class extends value "+String(t)+" is not a constructor or null");function n(){this.constructor=e}i(e,t),e.prototype=null===t?Object.create(t):(n.prototype=t.prototype,new n)}function a(e,t){return t={exports:{}},e(t,t.exports),t.exports}var u,s=a(function(e,t){function n(e){if(e&&"object"===typeof e){var t=e.which||e.keyCode||e.charCode;t&&(e=t)}if("number"===typeof e)return c[e];var n=String(e),i=r[n.toLowerCase()];if(i)return i;i=o[n.toLowerCase()];return i||(1===n.length?n.charCodeAt(0):void 0)}n.isEventKey=function(e,t){if(e&&"object"===typeof e){var n=e.which||e.keyCode||e.charCode;if(null===n||void 0===n)return!1;if("string"===typeof t){var i=r[t.toLowerCase()];if(i)return i===n;i=o[t.toLowerCase()];if(i)return i===n}else if("number"===typeof t)return t===n;return!1}},t=e.exports=n;var r=t.code=t.codes={backspace:8,tab:9,enter:13,shift:16,ctrl:17,alt:18,"pause/break":19,"caps lock":20,esc:27,space:32,"page up":33,"page down":34,end:35,home:36,left:37,up:38,right:39,down:40,insert:45,delete:46,command:91,"left command":91,"right command":93,"numpad *":106,"numpad +":107,"numpad -":109,"numpad .":110,"numpad /":111,"num lock":144,"scroll lock":145,"my computer":182,"my calculator":183,";":186,"=":187,",":188,"-":189,".":190,"/":191,"`":192,"[":219,"\\":220,"]":221,"'":222},o=t.aliases={windows:91,"⇧":16,"⌥":18,"⌃":17,"⌘":91,ctl:17,control:17,option:18,pause:19,break:19,caps:20,return:13,escape:27,spc:32,spacebar:32,pgup:33,pgdn:34,ins:45,del:46,cmd:91};
/*!
 * Programatically add the following
 */
for(i=97;i<123;i++)r[String.fromCharCode(i)]=i-32;for(var i=48;i<58;i++)r[i-48]=i;for(i=1;i<13;i++)r["f"+i]=i+111;for(i=0;i<10;i++)r["numpad "+i]=i+96;var c=t.names=t.title={};for(i in r)c[r[i]]=i;for(var a in o)r[a]=o[a]}),f=(s.code,s.codes,s.aliases,s.names),l=(s.title,{"+":"plus","left command":"meta","right command":"meta"}),y={shift:1,ctrl:2,alt:3,meta:4};function p(e,t){var n=(f[e]||t||"").toLowerCase();for(var r in l)n=n.replace(r,l[r]);return n.replace(/\s/g,"")}function d(e,t){void 0===t&&(t=p(e.keyCode,e.key));var n=h(e);return-1===n.indexOf(t)&&n.push(t),n.filter(Boolean)}function h(e){var t=[e.shiftKey&&"shift",e.ctrlKey&&"ctrl",e.altKey&&"alt",e.metaKey&&"meta"];return t.filter(Boolean)}function v(e){var t=e.slice();return t.sort(function(e,t){var n=y[e]||5,r=y[t]||5;return n-r}),t}var m=function(e){function t(t){void 0===t&&(t=window);var n=e.call(this)||this;return n.container=t,n.ctrlKey=!1,n.altKey=!1,n.shiftKey=!1,n.metaKey=!1,n.clear=function(){return n.ctrlKey=!1,n.altKey=!1,n.shiftKey=!1,n.metaKey=!1,n},n.keydownEvent=function(e){n.triggerEvent("keydown",e)},n.keyupEvent=function(e){n.triggerEvent("keyup",e)},n.blur=function(){n.clear(),n.trigger("blur")},(0,o.W2)(t,"blur",n.blur),(0,o.W2)(t,"keydown",n.keydownEvent),(0,o.W2)(t,"keyup",n.keyupEvent),n}c(t,e);var n=t.prototype;return Object.defineProperty(t,"global",{get:function(){return u||(u=new t)},enumerable:!1,configurable:!0}),t.setGlobal=function(){return this.global},n.destroy=function(){var e=this.container;this.clear(),this.off(),(0,o.Nn)(e,"blur",this.blur),(0,o.Nn)(e,"keydown",this.keydownEvent),(0,o.Nn)(e,"keyup",this.keyupEvent)},n.keydown=function(e,t){return this.addEvent("keydown",e,t)},n.offKeydown=function(e,t){return this.removeEvent("keydown",e,t)},n.offKeyup=function(e,t){return this.removeEvent("keyup",e,t)},n.keyup=function(e,t){return this.addEvent("keyup",e,t)},n.addEvent=function(e,t,n){return(0,o.cy)(t)?this.on("".concat(e,".").concat(v(t).join(".")),n):(0,o.Kg)(t)?this.on("".concat(e,".").concat(t),n):this.on(e,t),this},n.removeEvent=function(e,t,n){return(0,o.cy)(t)?this.off("".concat(e,".").concat(v(t).join(".")),n):(0,o.Kg)(t)?this.off("".concat(e,".").concat(t),n):this.off(e,t),this},n.triggerEvent=function(e,t){this.ctrlKey=t.ctrlKey,this.shiftKey=t.shiftKey,this.altKey=t.altKey,this.metaKey=t.metaKey;var n=p(t.keyCode,t.key),r="ctrl"===n||"shift"===n||"meta"===n||"alt"===n,o={key:n,isToggle:r,inputEvent:t,keyCode:t.keyCode,ctrlKey:t.ctrlKey,altKey:t.altKey,shiftKey:t.shiftKey,metaKey:t.metaKey};this.trigger(e,o),this.trigger("".concat(e,".").concat(n),o);var i=d(t,n);i.length>1&&this.trigger("".concat(e,".").concat(i.join(".")),o)},t}(r.A);
/*! *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */const g=m}};
//# sourceMappingURL=editor.npm.keycon_dist.566c3d.js.map