export const cssVars = {
    'caption-text_font-family': ['caption.style.fontFamily', 'var(--font-family)'],
    'caption-text_color': ['caption.style.color', 'inherit'],
    'caption-text_font-size': ['caption.style.fontSize', 'inherit'],
    'idp_bg-color': ['inputMode.style.background', 'var(--color-white)'],
    'idp_border-width': ['inputMode.style.borderWidth', '1px'],
    'idp_border-style': ['inputMode.style.borderStyle', 'solid'],
    'idp_border-color': ['inputMode.style.borderColor', 'var(--color-grey-light)'],
    'idp_border-radius': ['inputMode.style.borderRadius', '0.25rem'],
    'idp-input_color': ['inputMode.inpStyle.color', 'inherit'],
    'idp-input_font-size': ({ inputMode }) => inputMode.inpStyle['font-size'] || '100%',
    'idp-input_font-family': ({ inputMode }) => inputMode.inpStyle['font-family'] || 'inherit',
    'idp-icon_color': ['inputMode.icon.style.color', 'inherit'],
    'idp-icon_font-size': ({ inputMode }) => inputMode.icon.style['font-size'] || 'inherit',
    'idp-width': ['inputMode.style.width', 'inherit'],
    'idp-height': ['inputMode.style.height', 'inherit'],
    'idp-input-placeholder_color': ['inputMode.style.color', '#aaa'],
    'reset-btn-color': ['resetBtn.color', 'var(--color-white)'],
    'reset-btn-bgcolor': ['resetBtn.bgColor', 'var(--color-primary)'],
    'reset-btn-fontsize': ['resetBtn.fontSize'],
    'reset-btn-width': ['resetBtn.width'],
    'reset-btn-height': ['resetBtn.height'],
    'reset-btn-border-radius': ['resetBtn.borderRadius', '.25rem'],
    'reset-btn-mar-inline': ['resetBtn.marginInline'],
    'reset-btn-mar-block': ['resetBtn.marginBlock'],
    'reset-btn-align': ['resetBtn.align']
};
